package mondays.net.mroki.api.responseCode;

public enum ErrorCode {
    COMMENT_FAILED,
    ID_CATEGORY_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    LOGIN_FAIL,
    WRONG_USERNAME_OR_PASSWORD,
    PRODUCT_NAME_IS_EXIST,
    CONVERT_CATEGORY_ERROR,
    USERNAME_NOT_AVAILABLE,
    EMAIL_NOT_AVAILABLE,
    SIGN_UP_FAIL,
    GET_ALL_COMMENT_FAIL,
    ORDER_FAIL,
    GET_PRODUCT_FAIL,
    GET_PRODUCT_DETAIL_FAIL,
    CATEGORY_ID_NOT_AVAILABLE,
    CATEGORY_NOT_FOUND,
    PRODUCT_CONVERT_FAIL,
    SAVE_PRODUCT_FAIL,
    GET_SIZE_FAIL,
    ADD_PRODUCT_TO_CART_FAIL,
    DELETE_PRODUCT_IN_CART_FAIL,
    UPDATE_CATEGORY_FAIL

}
