package mondays.net.mroki.api.responseCode;

public enum ErrorCode {
    SIGN_UP_FAILED,
    ADD_PRODUCT_TO_CART,
    COMMENT_FAILED,
    ORDER,
    ID_CATEGORY_NOT_FOUND,
    ID_IS_EXISTS,
    GET_PRODUCT,
    GET_PRODUCT_DETAIL,
    GET_PRODUCT_BY_CATEGORY,
    PRODUCT_NOT_FOUND,
    SAVE_PRODUCT,
    GET_ALL_COMMENT
}
