package mondays.net.mroki.api.responseCode;

public enum SuccessCode {

    SIGN_UP_SUCCESS,
    COMMENT_SUCCESS,
    GET_ALL_COMMENT_SUCCESS,
    LOGIN_SUCCESS,
    ORDER_SUCCESS,
    GET_PRODUCT_SUCCESS,
    GET_PRODUCT_DETAIL_SUCCESS,
    SAVE_PRODUCT_SUCCESS,
    UPDATE_PRODUCT_SUCCESS,
    DELETE_PRODUCT_SUCCESS,
    GET_SIZE_SUCCESS,
    ADD_PRODUCT_TO_CART_SUCCESS,
    DELETE_PRODUCT_IN_CART_SUCCESS,
    UPDATE_CATEGORY_SUCCESS,
    DELETE_CATEGORY_SUCCESS,
    ADD_CATEGORY_SUCCESS



}
