package mondays.net.mroki.api.responseCode;

public enum SuccessCode {

    SIGN_UP_SUCCESS,
    ADD_PRODUCT_TO_CART,
    COMMENT_SUCCESS,
    ORDER,
    ADD_CATEGORY,
    DELETE_CATEGORY,
    UPDATE_CATEGORY,
    GET_PRODUCT,
    GET_PRODUCT_DETAIL,
    GET_PRODUCT_BY_CATEGORY,
    SAVE_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    GET_ALL_COMMENT,
    GET_SIZE
}
